package:
  name: auto-07p
  version: 0.9.1

source:
  fn: auto07p-0.9.1.tar.gz
  url: http://sourceforge.net/projects/auto-07p/files/auto07p/0.9/auto07p-0.9.1.tar.gz
  sha256: 8f306751521a491113f89ffbd8b20b68d72aeac42833fa196f2158f3bef35bca

requirements:
  build:
    - python {{ python }}
    - setuptools
  # TODO: maybe add compilers

  run:
    - python >=2.4

    - matplotlib <2  # auto.pdf says 0.99 or higher is recommended

    # python/demo2.auto didn't work with numpy 1.7.1
    - numpy <=1.6.99999

build:
  # Disable binary relocation.  It probably is not necessary (I could
  # run a dmoe without it) but I don't want magics of AUTO and conda
  # to be mixed at the moment.
  binary_relocation: False

about:
  home: http://cmvl.cs.concordia.ca/auto
